"""Bridge to the Einstein Toolkit for full numerical-relativity evolution.

Pure-Python evolution of the Einstein equations (BSSN / 3+1) is out of scope for
this package.  For dynamical studies — throat collapse, perturbed evolution — the
production path is the Einstein Toolkit (Cactus + Carpet AMR).  This module
generates a ready-to-run ET parameter (.par) file describing wormhole initial
data on a Cartesian grid, so the rest of the framework (geodesics, lensing,
diagnostics) can post-process the ET output.

It does NOT run ET (which requires an HPC build); it produces the .par the user
submits.
"""

from __future__ import annotations

import numpy as np


def wormhole_initial_data_grid(metric, half_width=20.0, n=64):
    """Sample the spatial 3-metric conformal factor on a Cartesian grid.

    Returns (X, Y, Z, psi) where psi approximates the conformal factor built from
    the areal radius, suitable for an ET 'read from file' initial-data thorn.
    """
    ax = np.linspace(-half_width, half_width, n)
    X, Y, Z = np.meshgrid(ax, ax, ax, indexing="ij")
    rho = np.sqrt(X ** 2 + Y ** 2 + Z ** 2) + 1e-6
    b0 = getattr(metric, "b0", 1.0)
    # areal radius for an Ellis-like throat -> conformal factor psi ~ (R/rho)^{1/2}
    R = np.sqrt(rho ** 2 + b0 ** 2)
    psi = np.sqrt(R / rho)
    return X, Y, Z, psi


def generate_par_file(metric, out_path="wormhole.par", final_time=50.0,
                      grid_half_width=20.0, resolution=64):
    """Write an Einstein Toolkit .par file for evolving wormhole initial data.

    Returns the path written.  The parameter set uses McLachlan (BSSN), Carpet
    AMR and the standard analysis thorns; initial data are flagged for an
    external reader (the grid from ``wormhole_initial_data_grid``).
    """
    b0 = getattr(metric, "b0", 1.0)
    dx = 2.0 * grid_half_width / resolution
    par = f"""# Einstein Toolkit parameter file (auto-generated by wormhole-sim)
# Metric: {type(metric).__name__}  (b0 = {b0})
ActiveThorns = "
    Carpet CarpetLib CarpetReduce CarpetRegrid2 CarpetInterp
    CartGrid3D CoordBase SymBase Boundary
    MoL Time InitBase
    ADMBase ADMCoupling ADMMacros StaticConformal
    ML_BSSN ML_BSSN_Helper GenericFD TmunuBase
    NaNChecker CarpetIOBasic CarpetIOScalar CarpetIOHDF5
"

Cactus::cctk_run_title = "Wormhole evolution (b0={b0})"
Cactus::terminate      = "time"
Cactus::cctk_final_time = {final_time}

CoordBase::domainsize = "minmax"
CoordBase::xmin = {-grid_half_width}
CoordBase::xmax = { grid_half_width}
CoordBase::ymin = {-grid_half_width}
CoordBase::ymax = { grid_half_width}
CoordBase::zmin = {-grid_half_width}
CoordBase::zmax = { grid_half_width}
CoordBase::dx = {dx:.5f}
CoordBase::dy = {dx:.5f}
CoordBase::dz = {dx:.5f}

Carpet::max_refinement_levels = 5
CarpetRegrid2::num_centres     = 1
CarpetRegrid2::num_levels_1    = 5
CarpetRegrid2::radius_1[1]     = {grid_half_width/2:.2f}
CarpetRegrid2::radius_1[2]     = {grid_half_width/4:.2f}

ADMBase::initial_data    = "read_from_file"   # supply wormhole_initial_data_grid()
ADMBase::initial_lapse   = "one"
ADMBase::evolution_method = "ML_BSSN"
ML_BSSN::my_initial_boundary_condition = "extrapolate-gammas"

MoL::ODE_Method = "RK4"
MoL::MoL_Intermediate_Steps = 4
Time::dtfac = 0.25

IOBasic::outInfo_every = 16
IOScalar::outScalar_every = 16
IOScalar::outScalar_vars = "ADMBase::gxx ML_BSSN::H"
NaNChecker::check_every = 16
NaNChecker::action_if_found = "terminate"
"""
    with open(out_path, "w") as f:
        f.write(par)
    return out_path
